### ISSUE TITLE
cosmovisor environment variables

### ISSUE THREAD

**Issue by nullmames** [polkachu/cosmos-validators#1]
If this ansible is meant for a validator, it is best practice to keef the default "false" value for binary download. it is considered a possible security vulnerability and should only be used on nodes.

So, at the very least, it should be made a variable for the ansible that needs to be set by the user and is default "false"

**Comment by husonghua** [comment]
Thanks. You are exactly right. I have just fixed it with the latest commit. I will work on the other issues you have submitted tomorrow. Thanks for reviewing this repo for me.

**Comment by nullmames** [comment]
thats a great outcome. thanks for considering this.
