### ISSUE TITLE
chore: utilize git module for fetch and checkout

### ISSUE THREAD

**Issue by pratikbin** [polkachu/cosmos-validators#14]
Use ansible git module to avoid manual command. Towards ansible way

https://github.com/polkachu/cosmos-validators/blob/5e261eb3ff9a6c9339ad958447e709e0c5eaf071/roles/node_install/tasks/main.yml#L4-L13

**Comment by pratikbin** [comment]
https://github.com/polkachu/cosmos-validators/pull/13

**Comment by PolkachuIntern** [comment]
Thanks. Did not know the git module.

By the way, I think I want to keep the "Make sure the folder does not exist" task. It is just cleaner in case of unlikely conflicts. Thoughts?

Will merge your chain either way though. git module is the right way to manage it.

**Comment by pratikbin** [comment]
> Thanks. Did not know the git module.

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html

> By the way, I think I want to keep the "Make sure the folder does not exist" task. It is just cleaner in case of unlikely conflicts. Thoughts?

Then `Clone node repo` will always state `changed`, which will fail idempotentcy test (I'm working on automated testing of this ansible), and technically it is not ansible way to do it.

**Comment by PolkachuIntern** [comment]
This improvement has been committed with https://github.com/polkachu/cosmos-validators/commit/ae29661f716afbabb49c55d7d10426ce5e886ac2.
