### ISSUE TITLE
setup environment suitable for cosmos sdk chains

### ISSUE THREAD

**Issue by nullmames** [polkachu/cosmos-validators#3]
update apt and upgrade to all latest packages.
install all required build packages with apt.
install latest version of go and set paths.

**Comment by joeabbey** [comment]
I think this is handled by the `prepare` role https://github.com/polkachu/cosmos-validators/blob/main/roles/prepare/tasks/cosmos_software.yml

**Comment by nullmames** [comment]
i missed this. thanks for pointing it out. i missed it cruising throuth the repo on my mobile.

**Comment by husonghua** [comment]
Close this issue. The new release improved README and explained better about the 'prepare' playbook. Closing the issue. Thanks!
