### ISSUE TITLE
crescent node config minimum_gas_price typo

### ISSUE THREAD

**Issue by silentnoname** [polkachu/cosmos-validators#37]
https://github.com/polkachu/cosmos-validators/blob/ddd398c7b52fdcdb1ac5f992b9a5f7544d03ff09/group_vars/mainnets/crescent.yml#L9

`minimum_gas_price: '0.01ucre,0.01bucre' ` should be `minimum_gas_price: '0.01ucre,0.01ubcre' `

**Comment by PolkachuIntern** [comment]
Thanks. Corrected it with this commit https://github.com/polkachu/cosmos-validators/commit/20a4fcd9eda848d6af19b735f4731eaa708188e8
