### ISSUE TITLE
Sample inventory lends itself to bug

### ISSUE THREAD

**Issue by ryantking** [polkachu/cosmos-validators#43]
The following lines in `inventory.sample` if followed too closely will cause bugs when running the main playbook:

```
[mainnets]
mainnet1 ansible_host=10.0.0.1
```

Specifically, since a folder in `group_vars` is named `mainnets` if an end user (me in this case) creates a group named `mainnets` like in the sample, all the files in that `group_vars/mainnets` folder will be applied, causing unexpected behavior.

**Comment by PolkachuIntern** [comment]
I see. Maybe rename it to "mainnet_group"?

**Comment by ryantking** [comment]
I would personally just remove this part of the sample inventory:

```ini
[mainnets]
mainnet1 ansible_host=10.0.0.1

[backups]
backup1 ansible_host=10.0.0.1

[relayers]
relayer1 ansible_host=10.0.0.3
```

The juno section that follows it more clearly demonstrates how to setup an inventory. The excerpt above adds  confusion because its a fair assumption that the groups (`mainnets`, `backups`, `relayers`) have configuration significance when they are not actually used by playbooks or group_vars. The testnet sample inventory is more self explanatory in my opinion.

**Comment by PolkachuIntern** [comment]
Makes sense. This commit fixes it https://github.com/polkachu/cosmos-validators/commit/158b427dfd53476efcc18b76551824bc9ccc7cd5
