### ISSUE TITLE
Feature request: make firewall optional

### ISSUE THREAD

**Issue by ryantking** [polkachu/cosmos-validators#44]
The firewall-related tasks assume the user is running the node on a publicly exposed machine. Some users may use a top-of-rack firewall or other solution and not wish to have UFW installed on the specific machine hosting the node. I understand that supporting alternative firewall solutions is probably out of scope for this project, but UFW should at the very least be opt out for users with special setups.

**Comment by ryantking** [comment]
I'll do the PR myself if the maintainers want to add this functionality

**Comment by PolkachuIntern** [comment]
Thanks for the comment and sorry about the delay. We intend to make this codebase opinionated and minimize complexity. Many users actually fork it into their own repo for their own customization. Pease feel free to do so. It is under MIT license, so you can do whatever.
